package com.jojos.challenge.iban.country;

/**
 * Enumeration defining all countries defined in ISO 3166-1 alpha-2
 *
 * @see <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">ISO_3166-1_alpha-2 format</a>
 *
 * Created by karanikasg@gmail.com.
 */
public enum CountryISO {
    PR("PUERTO RICO"),
    PS("PALESTINE, STATE OF"),
    PT("PORTUGAL"),
    PW("PALAU"),
    PY("PARAGUAY"),
    QA("QATAR"),
    AD("ANDORRA"),
    AE("UNITED ARAB EMIRATES"),
    AF("AFGHANISTAN"),
    AG("ANTIGUA AND BARBUDA"),
    AI("ANGUILLA"),
    AL("ALBANIA"),
    AM("ARMENIA"),
    AO("ANGOLA"),
    AQ("ANTARCTICA"),
    AR("ARGENTINA"),
    AS("AMERICAN SAMOA"),
    AT("AUSTRIA"),
    RE("RÉUNION"),
    AU("AUSTRALIA"),
    AW("ARUBA"),
    AX("ÅLAND ISLANDS"),
    AZ("AZERBAIJAN"),
    RO("ROMANIA"),
    BA("BOSNIA AND HERZEGOVINA"),
    BB("BARBADOS"),
    RS("SERBIA"),
    BD("BANGLADESH"),
    BE("BELGIUM"),
    RU("RUSSIAN FEDERATION"),
    BF("BURKINA FASO"),
    BG("BULGARIA"),
    RW("RWANDA"),
    BH("BAHRAIN"),
    BI("BURUNDI"),
    BJ("BENIN"),
    BL("SAINT BARTHÉLEMY"),
    BM("BERMUDA"),
    BN("BRUNEI DARUSSALAM"),
    BO("BOLIVIA, PLURINATIONAL STATE OF"),
    SA("SAUDI ARABIA"),
    BQ("BONAIRE, SINT EUSTATIUS AND SABA"),
    SB("SOLOMON ISLANDS"),
    BR("BRAZIL"),
    SC("SEYCHELLES"),
    BS("BAHAMAS"),
    SD("SUDAN"),
    BT("BHUTAN"),
    SE("SWEDEN"),
    BV("BOUVET ISLAND"),
    SG("SINGAPORE"),
    BW("BOTSWANA"),
    SH("SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA"),
    SI("SLOVENIA"),
    BY("BELARUS"),
    SJ("SVALBARD AND JAN MAYEN"),
    BZ("BELIZE"),
    SK("SLOVAKIA"),
    SL("SIERRA LEONE"),
    SM("SAN MARINO"),
    SN("SENEGAL"),
    SO("SOMALIA"),
    CA("CANADA"),
    SR("SURINAME"),
    CC("COCOS (KEELING) ISLANDS"),
    SS("SOUTH SUDAN"),
    CD("CONGO, THE DEMOCRATIC REPUBLIC OF THE"),
    ST("SAO TOME AND PRINCIPE"),
    CF("CENTRAL AFRICAN REPUBLIC"),
    SV("EL SALVADOR"),
    CG("CONGO"),
    SX("SINT MAARTEN (DUTCH PART)"),
    CH("SWITZERLAND"),
    CI("CÔTE D'IVOIRE"),
    SY("SYRIAN ARAB REPUBLIC"),
    SZ("SWAZILAND"),
    CK("COOK ISLANDS"),
    CL("CHILE"),
    CM("CAMEROON"),
    CN("CHINA"),
    CO("COLOMBIA"),
    CR("COSTA RICA"),
    TC("TURKS AND CAICOS ISLANDS"),
    TD("CHAD"),
    CU("CUBA"),
    TF("FRENCH SOUTHERN TERRITORIES"),
    CV("CAPE VERDE"),
    TG("TOGO"),
    CW("CURAÇAO"),
    TH("THAILAND"),
    CX("CHRISTMAS ISLAND"),
    CY("CYPRUS"),
    TJ("TAJIKISTAN"),
    CZ("CZECH REPUBLIC"),
    TK("TOKELAU"),
    TL("TIMOR-LESTE"),
    TM("TURKMENISTAN"),
    TN("TUNISIA"),
    TO("TONGA"),
    TR("TURKEY"),
    TT("TRINIDAD AND TOBAGO"),
    DE("GERMANY"),
    TV("TUVALU"),
    TW("TAIWAN, PROVINCE OF CHINA"),
    DJ("DJIBOUTI"),
    TZ("TANZANIA, UNITED REPUBLIC OF"),
    DK("DENMARK"),
    DM("DOMINICA"),
    DO("DOMINICAN REPUBLIC"),
    UA("UKRAINE"),
    UG("UGANDA"),
    DZ("ALGERIA"),
    UM("UNITED STATES MINOR OUTLYING ISLANDS"),
    EC("ECUADOR"),
    US("UNITED STATES"),
    EE("ESTONIA"),
    EG("EGYPT"),
    EH("WESTERN SAHARA"),
    UY("URUGUAY"),
    UZ("UZBEKISTAN"),
    VA("HOLY SEE (VATICAN CITY STATE)"),
    ER("ERITREA"),
    VC("SAINT VINCENT AND THE GRENADINES"),
    ES("SPAIN"),
    ET("ETHIOPIA"),
    VE("VENEZUELA, BOLIVARIAN REPUBLIC OF"),
    VG("VIRGIN ISLANDS, BRITISH"),
    VI("VIRGIN ISLANDS, U.S."),
    VN("VIETNAM"),
    VU("VANUATU"),
    FI("FINLAND"),
    FJ("FIJI"),
    FK("FALKLAND ISLANDS (MALVINAS)"),
    FM("MICRONESIA, FEDERATED STATES OF"),
    FO("FAROE ISLANDS"),
    FR("FRANCE"),
    WF("WALLIS AND FUTUNA"),
    GA("GABON"),
    GB("UNITED KINGDOM"),
    WS("SAMOA"),
    GD("GRENADA"),
    GE("GEORGIA"),
    GF("FRENCH GUIANA"),
    GG("GUERNSEY"),
    GH("GHANA"),
    GI("GIBRALTAR"),
    GL("GREENLAND"),
    GM("GAMBIA"),
    GN("GUINEA"),
    GP("GUADELOUPE"),
    GQ("EQUATORIAL GUINEA"),
    GR("GREECE"),
    GS("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"),
    GT("GUATEMALA"),
    GU("GUAM"),
    GW("GUINEA-BISSAU"),
    GY("GUYANA"),
    HK("HONG KONG"),
    HM("HEARD ISLAND AND MCDONALD ISLANDS"),
    HN("HONDURAS"),
    HR("CROATIA"),
    HT("HAITI"),
    YE("YEMEN"),
    HU("HUNGARY"),
    ID("INDONESIA"),
    YT("MAYOTTE"),
    IE("IRELAND"),
    IL("ISRAEL"),
    IM("ISLE OF MAN"),
    IN("INDIA"),
    IO("BRITISH INDIAN OCEAN TERRITORY"),
    ZA("SOUTH AFRICA"),
    IQ("IRAQ"),
    IR("IRAN, ISLAMIC REPUBLIC OF"),
    IS("ICELAND"),
    IT("ITALY"),
    ZM("ZAMBIA"),
    JE("JERSEY"),
    ZW("ZIMBABWE"),
    JM("JAMAICA"),
    JO("JORDAN"),
    JP("JAPAN"),
    KE("KENYA"),
    KG("KYRGYZSTAN"),
    KH("CAMBODIA"),
    KI("KIRIBATI"),
    KM("COMOROS"),
    KN("SAINT KITTS AND NEVIS"),
    KP("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"),
    KR("KOREA, REPUBLIC OF"),
    KW("KUWAIT"),
    KY("CAYMAN ISLANDS"),
    KZ("KAZAKHSTAN"),
    LA("LAO PEOPLE'S DEMOCRATIC REPUBLIC"),
    LB("LEBANON"),
    LC("SAINT LUCIA"),
    LI("LIECHTENSTEIN"),
    LK("SRI LANKA"),
    LR("LIBERIA"),
    LS("LESOTHO"),
    LT("LITHUANIA"),
    LU("LUXEMBOURG"),
    LV("LATVIA"),
    LY("LIBYA"),
    MA("MOROCCO"),
    MC("MONACO"),
    MD("MOLDOVA, REPUBLIC OF"),
    ME("MONTENEGRO"),
    MF("SAINT MARTIN (FRENCH PART)"),
    MG("MADAGASCAR"),
    MH("MARSHALL ISLANDS"),
    MK("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"),
    ML("MALI"),
    MM("MYANMAR"),
    MN("MONGOLIA"),
    MO("MACAO"),
    MP("NORTHERN MARIANA ISLANDS"),
    MQ("MARTINIQUE"),
    MR("MAURITANIA"),
    MS("MONTSERRAT"),
    MT("MALTA"),
    MU("MAURITIUS"),
    MV("MALDIVES"),
    MW("MALAWI"),
    MX("MEXICO"),
    MY("MALAYSIA"),
    MZ("MOZAMBIQUE"),
    NA("NAMIBIA"),
    NC("NEW CALEDONIA"),
    NE("NIGER"),
    NF("NORFOLK ISLAND"),
    NG("NIGERIA"),
    NI("NICARAGUA"),
    NL("NETHERLANDS"),
    NO("NORWAY"),
    NP("NEPAL"),
    NR("NAURU"),
    NU("NIUE"),
    NZ("NEW ZEALAND"),
    OM("OMAN"),
    PA("PANAMA"),
    PE("PERU"),
    PF("FRENCH POLYNESIA"),
    PG("PAPUA NEW GUINEA"),
    PH("PHILIPPINES"),
    PK("PAKISTAN"),
    PL("POLAND"),
    PM("SAINT PIERRE AND MIQUELON"),
    PN("PITCAIRN");

    private final String name;

    CountryISO(String name) {
        this.name = name;
    }

    public String getCode() {
        return name();
    }

    public String getName() {
        return name;
    }

    public static CountryISO forCaseInsensitiveCode(String code) {
        try {
            return Enum.valueOf(CountryISO.class, code.toUpperCase());
        } catch (IllegalArgumentException e) {
            return null;
        }
    }
}
